name: Github Action Workflow pour P13 OC

on:
  push:
    branches:
      - master # Déclenche uniquement lorsque des modifications sont apportées à la branche master

jobs:
  django-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 # Version Python

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test
