name: Github Action Workflow pour P13 OC

on: push
jobs:
  django-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 # Version Python

      - name: generate .env file
        run: | 
          echo DEBUG="${{ secrets.DEBUG }}" >> .env
          echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
          cat .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test
