name: Github Action Workflow pour P13 OC

on:
  push:
    branches: [ master ]

jobs:
  django-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 # Version Python

      - name: generate .env file
        run: | 
          echo DEBUG="${{ secrets.DEBUG }}" >> .env
          echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
          cat .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

      - name: Run litting
        run: flake8

  docker-build-and-push:
      runs-on: ubuntu-latest
      needs: django-tests
      if: github.ref == 'refs/heads/master'
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: generate .env file
          run: | 
            echo DEBUG="${{ secrets.DEBUG }}" >> .env
            echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
            cat .env
        - name: Login to Docker Hub
          run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and Push Docker image
          run: |
            docker build -t docker_oc_lettings:latest .
            docker tag docker_oc_lettings:latest glaxer/docker_oc_lettings:latest
            docker push glaxer/docker_oc_lettings:latest

